services:
  web:
    build: .
    environment:
      - DEBUG=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    volumes:
      - .:/app
  web_install:
    extends: web
    command: poetry install

  web_migrate:
    extends: web
    command: poetry run python manage.py migrate

  web_run:
    extends: web
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
     - "8000:8000"
    depends_on:
     - redis
     - db

  redis:
    image: redis:alpine
  
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres